name: reimch_launcher
description: Launcher from Reimch Project
publish_to: 'none'

version: 1.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_apps: ^2.2.0
  google_fonts: ^5.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

